export default {
    WAITTING_LOAD_DATA: 'WAITTING_LOAD_DATA',
    GET_CLASS_SUCCESS: 'GET_CLASS_SUCCESS',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    CHANGE_VALUE: 'CHANGE_VALUE'
};