export default {
    WAITTING_LOAD_DATA: 'WAITTING_LOAD_DATA',
    GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    CHANGE_VALUE: 'CHANGE_VALUE',
    CLOSE_MODAL_DELETE: 'CLOSE_MODAL_DELETE',
    OPEN_MODAL_DELETE: 'OPEN_MODAL_DELETE'
};